version: '3.1'
services:
  web:
    image: odoo:15.0
    replicas: 1
  	labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.wordpress.entrypoints: websecure
      traefik.http.routers.wordpress.rule: 'Host(`www.youtech-consulting.com`)'
      traefik.http.services.wordpress.loadbalancer.server.port: 80
volumes:
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/extra-addons
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
    restart: always
  mydb:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    restart: always
volumes:
  odoo-web-data:
    
  
