version: '3.1'
services:
  web:
    image: odoo:15.0
    replicas: 1
  	labels:
         - "traefik.port=80"
         - "traefik.weight=10"
         - "traefik.frontend.rule=PathPrefixStrip:/;"
         - "traefik.docker.network=wp"
         - "traefik.frontend.entryPoints=https"
         - "traefik.enable=true"
         - "traefik.passHostHeader=true"
         - "traefik.backend=wordpress"
         - "traefik.backend.loadbalancer.method=drr"
         - "traefik.backend.loadbalancer.stickiness=true"
         - "traefik.backend.loadbalancer.stickiness.cookieName=wp-monster"
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/extra-addons
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
    restart: always
  mydb:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    restart: always
volumes:
  odoo-web-data:
    
  
