version: '3.1'
services:
  web:
    image: odoo:15.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/usr/lib/python3/dist-packages/odoo/addons
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
    restart: always
  mydb:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      - ./pg_hba.conf:/var/lib/postgresql/data/pgdata/pg_hba.conf
    restart: always
volumes:
  odoo-web-data:
  odoo-db-data:
